# Generated by Django 5.2.7 on 2025-10-07 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('capacidad', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=20)),
                ('plan', models.CharField(choices=[('matematica', 'Matemática'), ('comunicacion', 'Comunicación'), ('ambos', 'Matemática + Comunicación')], max_length=50)),
                ('cupo_maximo', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lun', 'Lunes'), ('mar', 'Martes'), ('mie', 'Miércoles'), ('jue', 'Jueves'), ('vie', 'Viernes'), ('sab', 'Sábado'), ('dom', 'Domingo')], max_length=3)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'unique_together': {('dia', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docentes.aula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docentes.curso')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docentes.horario')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docentes.profesor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profesor', 'horario'), name='uniq_profesor_horario'), models.UniqueConstraint(fields=('aula', 'horario'), name='uniq_aula_horario')],
            },
        ),
    ]
