# Generated by Django 5.2.7 on 2025-11-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='grado',
            field=models.CharField(blank=True, choices=[('1° Prim', '1° Primaria'), ('2° Prim', '2° Primaria'), ('3° Prim', '3° Primaria'), ('4° Prim', '4° Primaria'), ('5° Prim', '5° Primaria'), ('6° Prim', '6° Primaria'), ('1° Sec', '1° Secundaria'), ('2° Sec', '2° Secundaria'), ('3° Sec', '3° Secundaria'), ('4° Sec', '4° Secundaria'), ('5° Sec', '5° Secundaria')], max_length=10, null=True),
        ),
    ]
