# Generated by Django 5.2.7 on 2025-11-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_asignacion_grado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('lun', 'Lunes'), ('mar', 'Martes'), ('mie', 'Miércoles'), ('jue', 'Jueves'), ('vie', 'Viernes'), ('sab', 'Sábado'), ('dom', 'Domingo')], max_length=3, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='curso',
            name='cupo_maximo',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='horario',
            name='dias',
            field=models.ManyToManyField(related_name='horarios', to='docentes.dia'),
        ),
        migrations.RemoveField(
            model_name='horario',
            name='dia',
        ),
    ]
