# Generated by Django 5.2.7 on 2025-11-24 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0003_dia_alter_horario_unique_together_and_more'),
        ('planes', '0004_remove_plan_cupo_maximo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='plan',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='planes.plan'),
        ),
    ]
