# Generated by Django 5.2.7 on 2025-11-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0004_remove_asignacion_curso_remove_curso_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='nivel',
        ),
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
