# Generated by Django 5.2.7 on 2025-12-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0005_remove_curso_nivel_curso_descripcion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asignacion',
            name='uniq_profesor_horario',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='profesor',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='profesores',
            field=models.ManyToManyField(related_name='asignaciones', to='docentes.profesor'),
        ),
    ]
