# Generated by Django 5.2.9 on 2025-12-04 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0006_remove_asignacion_uniq_profesor_horario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'verbose_name': 'Asignación', 'verbose_name_plural': 'Asignaciones'},
        ),
        migrations.AlterModelOptions(
            name='aula',
            options={'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='dia',
            options={'verbose_name': 'Día', 'verbose_name_plural': 'Días'},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.RemoveConstraint(
            model_name='asignacion',
            name='uniq_aula_horario',
        ),
    ]
