# Generated by Django 5.2.9 on 2025-12-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0007_alter_asignacion_options_alter_aula_options_and_more'),
        ('planes', '0006_remove_plan_area_plan_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo en soles de esta asignación (por alumno).', max_digits=7, verbose_name='Precio'),
        ),
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.UniqueConstraint(fields=('aula', 'horario'), name='uniq_aula_horario'),
        ),
    ]
