# Generated by Django 5.2.9 on 2025-12-05 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0008_asignacion_precio_asignacion_uniq_aula_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo en soles de esta asignación (por alumno).', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
        ),
    ]
