# Generated by Django 5.2.7 on 2025-10-07 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia'), ('yape', 'Yape'), ('plin', 'Plin')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], max_length=20)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.inscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pagos.pago')),
            ],
        ),
    ]
