# Generated by Django 5.2.7 on 2025-11-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_comprobante_fecha_alter_comprobante_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
