# Generated by Django 5.2.7 on 2025-11-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_pago_options_alter_pago_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={},
        ),
        migrations.AddField(
            model_name='pago',
            name='estado_solicitado',
            field=models.CharField(choices=[('parcial', 'Parcial'), ('completado', 'Completado')], default='parcial', help_text='Lo que el apoderado indicó (parcial o completado). No cambia a menos que lo edites.', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=20),
        ),
    ]
