# Generated by Django 5.2.7 on 2025-10-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nivel', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=15)),
                ('area', models.CharField(choices=[('matematica', 'Matemática'), ('comunicacion', 'Comunicación'), ('ambos', 'Matemática + Comunicación')], max_length=15)),
                ('cupo_maximo', models.PositiveIntegerField(default=30)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
