# Generated by Django 5.2.7 on 2025-11-19 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_seed_default_plans_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='cupo_maximo',
        ),
    ]
