# Generated by Django 5.2.7 on 2025-11-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0004_remove_asignacion_curso_remove_curso_plan_and_more'),
        ('planes', '0004_remove_plan_cupo_maximo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='planes', to='docentes.curso'),
        ),
    ]
