# Generated by Django 5.2.7 on 2025-11-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0005_plan_cursos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='area',
        ),
        migrations.AddField(
            model_name='plan',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
