# Generated by Django 5.2.7 on 2025-10-07 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apoderados', '0001_initial'),
        ('docentes', '0001_initial'),
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=20)),
                ('monto_referencial', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('edad', models.PositiveIntegerField()),
                ('grado', models.CharField(choices=[('1° Prim', '1° Primaria'), ('2° Prim', '2° Primaria'), ('3° Prim', '3° Primaria'), ('4° Prim', '4° Primaria'), ('5° Prim', '5° Primaria'), ('6° Prim', '6° Primaria'), ('1° Sec', '1° Secundaria'), ('2° Sec', '2° Secundaria'), ('3° Sec', '3° Secundaria'), ('4° Sec', '4° Secundaria'), ('5° Sec', '5° Secundaria')], max_length=10)),
                ('colegio', models.CharField(max_length=150)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='apoderados.apoderado')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('total', 'Total'), ('parcial', 'Parcial')], max_length=20)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docentes.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
                ('plan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planes.plan')),
            ],
        ),
    ]
