# Generated by Django 5.2.7 on 2025-10-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='usuario_registra',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='usuario_registra',
        ),
    ]
