# Generated by Django 5.2.7 on 2025-10-09 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoderados', '0002_apoderado_dni'),
        ('estudiantes', '0003_remove_inscripcion_usuario_registra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='apoderado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='apoderados.apoderado'),
        ),
    ]
