# Generated by Django 5.2.7 on 2025-10-09 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
        ('estudiantes', '0004_alter_estudiante_apoderado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='docentes.curso'),
        ),
    ]
