# Generated by Django 5.2.7 on 2025-10-23 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_alter_inscripcion_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='edad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
