# Generated by Django 5.2.7 on 2025-10-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_alter_estudiante_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('anulada', 'Anulada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('total', 'Total')], default='pendiente', max_length=20),
        ),
    ]
