# Generated by Django 5.2.7 on 2025-10-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0007_inscripcion_estado_alter_inscripcion_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='verificada',
            field=models.BooleanField(default=False),
        ),
    ]
