# Generated by Django 5.2.7 on 2025-10-27 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0008_inscripcion_verificada'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='estudiantes.estudiante')),
            ],
        ),
    ]
