# Generated by Django 5.2.8 on 2025-11-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0009_verificaciontoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='access_code',
            field=models.CharField(blank=True, db_index=True, help_text='Código de acceso para seguimiento/regularización del pago.', max_length=16),
        ),
    ]
