# Generated by Django 5.2.8 on 2025-11-08 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0011_alter_inscripcion_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificaciontoken',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='access_code',
            field=models.CharField(blank=True, help_text='Código de acceso para seguimiento/regularización del pago.', max_length=16, null=True, unique=True),
        ),
    ]
