# Generated by Django 5.2.8 on 2025-11-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
        ('estudiantes', '0012_verificaciontoken_creado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='asignaciones',
            field=models.ManyToManyField(blank=True, related_name='matriculas', to='docentes.asignacion'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='inactivo', max_length=20),
        ),
    ]
