# Generated by Django 5.2.7 on 2025-11-19 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0003_dia_alter_horario_unique_together_and_more'),
        ('estudiantes', '0013_matricula_asignaciones_alter_matricula_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones', to='docentes.asignacion'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='provisional',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
