# Generated by Django 5.2.9 on 2025-12-04 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0014_inscripcion_asignacion_inscripcion_provisional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='verificaciontoken',
            options={'verbose_name': 'Token de verificación', 'verbose_name_plural': 'Tokens de verificación'},
        ),
    ]
