# Generated by Django 5.2.7 on 2025-10-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoderados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='dni',
            field=models.CharField(default=0, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
